language: node_js

node_js:
  - "8"

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test-only

after_success:
  - npm run typedoc
  - npm pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "leanix-js-*.tgz"
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: npm
    skip_cleanup: true
    email: "pauloramires@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
      all_branches: true

